// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Qualinea.Data;

#nullable disable

namespace Qualinea.Migrations
{
    [DbContext(typeof(DataDbContext))]
    [Migration("20220803214559_migration5")]
    partial class migration5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("Qualinea.Models.Analista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Analistas");
                });

            modelBuilder.Entity("Qualinea.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("Qualinea.Models.Insumo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Grupo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Insumos");
                });

            modelBuilder.Entity("Qualinea.Models.RegistroLaudo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Brix")
                        .HasColumnType("REAL");

                    b.Property<int?>("Cor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CorConcentrado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CorDiluicao")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Dimensao")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Granulometria")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdAnalista")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdFornecedor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdInsumo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InspecaoVisual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lote")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Medida")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotaFiscal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Odor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OdorConcentrado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OdorDiluicao")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Particulas")
                        .HasColumnType("REAL");

                    b.Property<float?>("Peso")
                        .HasColumnType("REAL");

                    b.Property<float?>("Ph")
                        .HasColumnType("REAL");

                    b.Property<int>("ResultadoFinal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Sabor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SaborDiluicao")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Solidificacao")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Temperatura")
                        .HasColumnType("REAL");

                    b.Property<int?>("Textura")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Umidade")
                        .HasColumnType("REAL");

                    b.Property<int?>("Vedacao")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Viscosidade")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("RegistroLaudos");
                });
#pragma warning restore 612, 618
        }
    }
}
